### PR TITLE
This is 2016

### PR DESCRIPTION
**Pull request by lexazloy**

### CODE REVIEW

**Comment by Mange** [comment]
I hope this gets accepted. We need to be a welcoming community where everyone feels empowered to contribute without the racist capitalist Patriarchy interfering with the myth of meritocracy.

If it's not accepted, the maintainers might need to add a Code of Conduct saying that it's okay to ban the owners if some commenter here feels unsafe.

**Comment by lexazloy** [comment]
\*jazz hands*

**Comment by fche** [comment]
"jazz hands" is ableist. check your privilege again, again.

**Comment by ErisBlastar** [comment]
No code of conduct, no deleting the repository. No racist capitalist Patriarch here here. Repository was mirrored from Bitbucket to preserve the sarcasm and humor.

**Pull request closed without merging**
